Global Holy Deletion
dipu-bd/lightnovel-crawler pull request #1583
Opened 2022-09-15 22:09 UTC by idMysteries

OMG, I did something terrible. But it's beautiful.

2022-09-15 22:10 UTC, idMysteries commented
310 changed files @dipu-bd 
AHAHAHAH

2022-09-18 16:36 UTC, dipu-bd requested changes

2022-09-18 16:36 UTC, dipu-bd commented on lncrawl/binders/__init__.py
> +
it would be better if it did not have these unnecessary newlines

2022-09-18 16:36 UTC, dipu-bd commented on sources/es/domentranslations.py
> +
changing sources will cause all users to get a force update. imagine you are running the app for a quick use, and having to wait for 300+ crawlers to fnish downloading. we should not modify all sources for just removing comments

2022-09-18 17:24 UTC, closed without merging